//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMMNM_sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaocaoDL
    {
        public BaocaoDL()
        {
            this.CTBCDLs = new HashSet<CTBCDL>();
        }
    
        public int IdBC { get; set; }
        public System.DateTime Ngay { get; set; }
        public int IdDL { get; set; }
    
        public virtual Daili Daili { get; set; }
        public virtual ICollection<CTBCDL> CTBCDLs { get; set; }
    }
}
