//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMMNM_sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPN
    {
        public int IdPn { get; set; }
        public int IdSach { get; set; }
        public int SoLuong { get; set; }
    
        public virtual Phieunhap Phieunhap { get; set; }
        public virtual Sach Sach { get; set; }
    }
}
