//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMMNM_sach.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daili
    {
        public Daili()
        {
            this.Phieuxuats = new HashSet<Phieuxuat>();
            this.BaocaoDLs = new HashSet<BaocaoDL>();
            this.Congnoes = new HashSet<Congno>();
            this.KhoDLs = new HashSet<KhoDL>();
        }
    
        public int IdDL { get; set; }
        public string TenDL { get; set; }
        public string DiaChi { get; set; }
        public string SDT { get; set; }
    
        public virtual ICollection<Phieuxuat> Phieuxuats { get; set; }
        public virtual ICollection<BaocaoDL> BaocaoDLs { get; set; }
        public virtual ICollection<Congno> Congnoes { get; set; }
        public virtual ICollection<KhoDL> KhoDLs { get; set; }
    }
}
