//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XDPMMNM_sach.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Model1Container : DbContext
    {
        public Model1Container()
            : base("name=Model1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NXB> NXBs { get; set; }
        public virtual DbSet<Daili> Dailis { get; set; }
        public virtual DbSet<Sach> Saches { get; set; }
        public virtual DbSet<Phieunhap> Phieunhaps1 { get; set; }
        public virtual DbSet<CTPN> CTPNs { get; set; }
        public virtual DbSet<Phieuxuat> Phieuxuats { get; set; }
        public virtual DbSet<CTPX> CTPXes { get; set; }
        public virtual DbSet<Kho> Khoes { get; set; }
        public virtual DbSet<BaocaoDL> BaocaoDLs { get; set; }
        public virtual DbSet<CTBCDL> CTBCDLs { get; set; }
        public virtual DbSet<Congno> Congnoes { get; set; }
        public virtual DbSet<KhoDL> KhoDLs { get; set; }
        public virtual DbSet<NoNXB> NoNXBs { get; set; }
    }
}
